[window]
option_as_alt = "OnlyLeft"

[font]
size = 10

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[general]
import = [
	"~/.config/alacritty/theme.toml"
]

# [[hints.enabled]]
# regex = "[^\\s]+\\.[a-zA-Z0-9]{1,6}(?::[0-9]+)?"
# command = { program = "alacritty", args = ["-e", "/home/tylercecil/bin/open_at_line.sh"] }
# mouse = { enabled = true, mods = "Control" }

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
