
[window]
option_as_alt = "OnlyLeft"

[font]
size = 14

[font.bold]
family = "SauceCodePRo Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePRo Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePRo Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePRo Nerd Font"
style = "Regular"

[general]
import = [
	"~/.config/alacritty/theme.toml"
]

# [[hints.enabled]]
# regex = "[^ ]+\\.go:\\d+"
# command = { program = "nvim", args = [] }
# mouse = { enabled = true }

