# UI Config
add-highlighter global/ number-lines -relative -hlcursor
set global ui_options ncurses_assistant=none

# buffer.kak Settings
# hook global WinDisplay .* info-buffers
# 
# map global user b ':enter-buffers-mode<ret>'              -docstring 'buffers…'
# map global user B ':enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'
# 
# alias global bd delete-buffer
# alias global bf buffer-first
# alias global bl buffer-last
# alias global bo buffer-only
# alias global bo! buffer-only-force

# LSP Settings
eval %sh{kak-lsp --kakoune -s $kak_session}
set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"
hook global WinSetOption filetype=(haskell) %{
    lsp-enable-window
    # lsp-auto-hover-enable
    set-option global lsp_auto_highlight_references true
    set-option global lsp_hover_anchor true
    set-option global lsp_hover_max_lines 15
    map -docstring "LSP Mode" global user l ': enter-user-mode lsp<ret>'
}

# Emacs editing keystrokes
map global insert <c-a> '<a-;>gh' 
map global insert <c-e> '<a-;>gl'
map global insert <c-left> '<a-;>b<a-;>;' 
map global insert <c-right> '<a-;>w<a-;>;'

map global normal <c-a> 'gh' 
map global normal <c-e> 'gl'
map global normal <c-left> 'b' 
map global normal <c-right> 'w'
