# Using plug.kak.
# Not strictly necessary, but perhaps cleaner.
source "%val{config}/plugins/plug.kak/rc/plug.kak"

add-highlighter global/ number-lines -relative

# LSP Settings
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable
map -docstring "LSP Mode" global user l ': enter-user-mode lsp<ret>'
