LSTOOL=eza

LSTOOL_BASEFLAGS="--group-directories-first"
LSTOOL_LONGFLAGS="--long --git"


alias ls="$LSTOOL $LSTOOL_BASEFLAGS"
alias sl="$LSTOOL $LSTOOL_BASEFLAGS"
alias la="$LSTOOL -a $LSTOOL_BASEFLAGS $LSTOOL_LONGFLAGS"
alias ll="$LSTOOL $LSTOOL_BASEFLAGS $LSTOOL_LONGFLAGS"
alias l="$LSTOOL $LSTOOL_BASEFLAGS $LSTOOL_LONGFLAGS"

export LS_COLORS=''
