#Load .Xresources to style emacs / urxvt / ect...
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

#Call xmodmap to configure keyboard
xmodmap .Xmodmaprc

#Set the typematic delay and rate
xset r rate 250 30    #A 250ms delay, and 30Hz repeat

#Set mouse pointer
xsetroot -cursor_name left_ptr

#Set desktop using feh
feh --bg-center ~/Pictures/Wallpaper/colorsanddots.jpg

#Start compton for composting (allows transperancy)
#Compton hangs with -b... not sure why. This will do.
compton --config ~/.config/compton.conf &

#Start xmonad. Will kill X when xmonad quits
exec xmonad
